import { WorkspaceLanguage } from '@/types/models';

export const UI_MESSAGES = {
  ko: {
    // P4-C Modals Extended
    'board.approval.approvedAlert': '승인 처리되었습니다.',
    'board.approval.rejectReasonRequired': '반려 시에는 사유를 반드시 입력해야 합니다.',
    'board.approval.rejectedAlert': '반려 처리되었습니다.',
    'board.approval.title': '결재 처리',
    'board.approval.reqTitle': '신청 제목',
    'board.approval.detailReason': '상세 사유',
    'board.approval.hopeDate': '희망 일정',
    'board.approval.reviewComment': '검토 의견 (선택)',
    'board.approval.reviewCommentPlaceholder': '승인/반려에 대한 추가 의견을 입력해주세요.',
    'board.approval.reject': '반려',
    'board.approval.approve': '승인',
    'board.status.waiting': '작업 착수 대기',
    'board.status.qcPmStart': 'QC/PM작업착수',
    'board.status.inProgress': '진행중',
    'board.status.pmReview': 'PM검토',
    'board.status.qcReview': 'QC검토',
    'board.status.done': '완료',
    'board.column.todo': '📥 수주/대기',
    'board.column.review': '🔎 QC/검수',
    'board.column.done': '✅ 완료',
    'board.deadline.1week': '🔴 납품 1주일 전',
    'board.deadline.2weeks': '🟠 납품 2주일 전',
    'board.deadline.1month': '🔵 납품 1달 전',
    'board.deadline.unset': '⚪ 미정',
    'board.assignee.unassigned': '미배정',
    'board.alert.noAssign': '작업자는 타인에게 업무를 배정할 수 없습니다.',
    'board.alert.onlyOwn': '자신의 업무카드만 이동할 수 있습니다.',
    'board.alert.noSkip': '공정 단계를 건너뛰어 이동할 수 없습니다.',
    'board.column.avg': '평균',
    'board.column.delayed': '지연',
    'board.column.urgent': '긴급',
    'board.column.pending': '대기',
    'board.dispatch.alertNoLang': '언어를 감지할 수 없습니다. 한국어 또는 베트남어로 명확히 입력해주세요.',
    'board.dispatch.translating': '번역 중...',
    'board.dispatch.alertNoTask': '최소 1개 이상의 업무를 추가해야 합니다.',
    'board.dispatch.alertMissingFields': '모든 업무의 제목, 담당자, 시작/마감일, 소요시간을 입력해야 합니다.',
    'board.dispatch.alertInvalidDate': '시작일은 마감일보다 늦을 수 없습니다.',
    'board.dispatch.alertDeadlineExceeded': '일부 업무의 마감일이 프로젝트의 최종 기한({projectLimit})을 초과합니다. 계속하시겠습니까?',
    'board.dispatch.modalTitle': 'PM 업무 하달 (Task Dispatch)',
    'board.dispatch.prevRejectReason': '이전 반려 사유',
    'board.dispatch.noReason': '사유 없음',
    'board.dispatch.extOrder': '외부 수주',
    'board.dispatch.internalDev': '개발팀 작업',
    'board.dispatch.pmInCharge': '담당 PM:',
    'board.dispatch.finalDeadline': '최종 기한:',
    'board.dispatch.taskListTitle': '세부 업무(Task) 생성 목록',
    'board.dispatch.addTask': '업무 추가',
    'board.dispatch.taskName': '업무명 *',
    'board.dispatch.taskNamePlaceholder': '업무명 입력',
    'board.dispatch.autoTranslate': '자동번역',
    'board.dispatch.assignee': '담당 작업자 *',
    'board.dispatch.assigneeSelect': '담당자 선택',
    'board.dispatch.priority': '우선순위',
    'board.dispatch.priUrgent': '긴급',
    'board.dispatch.priHigh': '높음',
    'board.dispatch.priNormal': '보통',
    'board.dispatch.priLow': '낮음',
    'board.dispatch.estTime': '소요 시간(예상) *',
    'board.dispatch.startDate': '시작 예정일 *',
    'board.dispatch.endDate': '마감일 *',
    'board.dispatch.warnOffDays': '해당 기간에 작업자의 휴가(OFF) 일정이 포함되어 있습니다.',
    'board.dispatch.warnOverload': '기존 업무 포함 일일 평균 예상 부하가 8시간을 초과합니다 ({avgDaily}h/day).',
    'board.dispatch.langKoDetected': '한국어 감지됨 · VI 번역 예정',
    'board.dispatch.langViDetected': '베트남어 감지됨 · KO 번역 예정',
    'board.dispatch.langUnknown': '알 수 없음',
    'board.dispatch.inputLanguage': '입력 언어:',
    'board.dispatch.transFailed': '(번역 실패)',
    'board.dispatch.limitExceeded': '한도 초과',
    'board.dispatch.submitRetry': '업무 일정 재요청',
    'board.dispatch.submitNew': '업무 하달 및 진행 전환',
    'board.process.noReason': '사유가 기재되지 않았습니다.',
    'board.process.alertSelectManager': '승인권자(매니저)를 선택해주세요.',
    'board.process.confirmSubmit': '승인을 요청하시겠습니까?',
    'board.process.reqTitle': '[공정 승인 요청] {title}',
    'board.process.reqReason': '공정 템플릿 기반 세부 소요일정 승인 요청',
    'board.process.alertRequested': '중간관리자에게 승인을 요청했습니다.',
    'board.process.noTemplateTitle': '공정 템플릿 미적용',
    'board.process.noTemplateDesc': '이 업무에 적용된 공정 템플릿이 없습니다. 템플릿을 적용하여 세부 일정을 계획하세요.',
    'board.process.selectTemplate': '템플릿 선택...',
    'board.process.apply': '적용',
    'board.process.rejected': '승인 반려됨',
    'board.process.rewrite': '일정을 다시 수정하기 (Draft)',
    'board.process.scheduleChart': '공정 일정표 (진행 중)',
    'board.process.status': '상태:',
    'board.process.selectApprover': '승인권자 선택...',
    'board.process.reqApproval': '승인 요청',
    'board.process.defaultAssign': '기본 할당:',
    'board.process.assigneeLabel': '담당자',
    'board.process.select': '선택...',
    'board.process.startLabel': '시작일',
    'board.process.endLabel': '종료일',
    'board.process.estLabel': '예상(h)',
    'board.process.detailPlaceholder': '세부 지시사항...',
    'board.project.noProject': '프로젝트가 없습니다',
    'board.part.noPart': '배정된 업무 파트가 없습니다.',
    'board.part.dispatchBtn': '세부 업무 및 파트 배정하기',
    'board.part.confirmApprove': '작성된 일정 계획을 승인하고 공식 일정으로 반영하시겠습니까?',
    'board.part.promptReject': '반려 사유를 입력해주세요:',
    'board.part.reqManagerReview': '부서장(MANAGER) 검수 요청',
    'board.part.waitApprovalDesc': 'PM이 작성한 세부 소요일정 승인 대기 중입니다.',
    'board.part.rejectSchedule': '일정 반려',
    'board.part.approveSchedule': '일정 승인 및 반영',
    'board.part.previewTitle': '승인 대기 일정 Preview & 직원별 부하 분석',
    'board.part.conflictCountAlert': '{conflictCount}건의 업무에서 일정 겹침(휴가 또는 과부하)이 발견되었습니다. 주의하여 승인해주세요.',
    'board.part.thTask': '업무명',
    'board.part.thAssignee': '담당자',
    'board.part.thPeriod': '기간',
    'board.part.thEst': '예상 소요',
    'board.part.thConflict': '충돌 분석',
    'board.part.conflictOff': '휴가 겹침',
    'board.part.conflictOverload': '과부하 ({avgDaily}h/d)',
    'board.part.conflictOk': '정상',
    'board.part.rejectedAlert': '작성하신 일정이 관리자에 의해 반려되었습니다. 수정 후 재요청이 필요합니다.',
    'board.part.rewriteRetry': '일정 수정 및 재요청',
    'board.part.taskCount': '{count}건',
    'board.part.participantCount': '참여 {count}명',
    'board.part.progressPercent': '진행률 {percent}%',
    'board.part.statusPending': '승인대기',
    'board.part.statusRejected': '반려됨',
    'board.part.taskDone': '작업 완료',
    'board.part.noTasks': '등록된 업무 카드가 없습니다.',
    'board.summary.sourceOrder': '수주',
    'board.summary.sourceInternal': '내부개발',
    'board.summary.pmUnset': '담당자 미정',
    'board.summary.targetTarget': '{date} 목표',
    'board.summary.targetDelivery': '{date} 납품',
    'board.summary.progress': '진행률',
    'board.summary.pendingTasks': '잔여 {count}건',
    'board.summary.addRequests': '추가업무 {count}건',
    'board.summary.revisions': '수정요청 {count}건',
    'board.summary.finalApprove': '최종 완료 승인',
    'board.revision.alertReqFields': '제목과 상세 내용을 입력해주세요.',
    'board.revision.alertSubmitted': '수정(Revision) 요청이 접수되었습니다.',
    'board.revision.title': '수정(Revision) 요청',
    'board.revision.targetProject': '대상 프로젝트',
    'board.revision.reqTitleLabel': '수정 요청 제목 *',
    'board.revision.reqTitlePlaceholder': '예) 로그인 페이지 로고 변경',
    'board.revision.reqDescLabel': '수정 요청 상세 내용 *',
    'board.revision.reqDescPlaceholder': '클라이언트가 요청한 구체적인 수정 내용을 입력해주세요.',
    'board.revision.submit': '요청 등록',
    'board.schedReq.extTitle': '일정 연장 신청',
    'board.schedReq.overtimeTitle': '추가 작업시간(야근) 신청',
    'board.schedReq.supportTitle': '인력 지원 요청',
    'board.schedReq.replanTitle': '세부 작업일정 조정 요청',
    'board.schedReq.defaultTitle': '신청',
    'board.schedReq.alertReqReason': '신청 사유를 입력해주세요.',
    'board.schedReq.alertSubmitted': '신청이 완료되었습니다.',
    'board.schedReq.targetTask': '대상 업무',
    'board.schedReq.currentSched': '현재 일정',
    'board.schedReq.hopeStart': '희망 시작일',
    'board.schedReq.hopeEnd': '희망 마감일',
    'board.schedReq.reasonLabel': '신청 사유 *',
    'board.schedReq.reasonPlaceholder': '구체적인 사유를 입력해주세요.',
    'board.schedReq.submit': '제출하기',
    'board.card.autoTransLabel': '[{lang} 자동번역] {text}',
    'board.card.orgTextLabel': '[{lang} 원문] {text}',
    'board.card.noTransLabel': '({lang} 번역 불가)',
    'board.card.postWork': '추가업무',
    'board.card.delayed': '지연',
    'board.card.pendingApprove': '승인 대기',
    'board.card.needReview': '검토필요',
    'board.card.approvedTrans': '승인번역',
    'board.card.billingLabel': '외주 비용: {amount}원',
    'board.card.outsourced': '외주',
    'board.card.tooltipAssignee': '담당자',
    'board.card.tooltipDeadline': '마감일',
    'board.detail.alertProgressNote': '진행률이 크게 변경되었습니다. 진행 내용에 상세한 메모를 남겨주세요 (5자 이상).',
    'board.detail.alertNoteSaved': '진행 내용이 기록되었습니다.',
    'board.detail.alertStartInvalid': '세부 작업 시작일은 카드의 시작일보다 빠를 수 없습니다.',
    'board.detail.alertEndInvalid': '세부 작업 종료일은 카드의 마감일보다 늦을 수 없습니다.',
    'board.detail.alertFileLarge': '\'{name}\'의 용량이 10MB를 초과합니다.',
    'board.detail.alertFileInvalid': '\'{name}\'은 지원하지 않는 파일 형식입니다. (PDF, JPG, PNG, XLSX, DOCX 허용)',
    'board.detail.promptAppeal': '해당 QC 결과(가중치 등)에 대한 이의신청 사유를 구체적으로 작성해주세요.',
    'board.detail.alertAppealSubmitted': '이의신청이 접수되었습니다. 관리자가 검토 후 재조정 여부를 결정합니다.',
    'board.detail.tabOverview': '개요',
    'board.detail.tabProcess': '공정 템플릿',
    'board.detail.tabSegments': '세부 작업내역',
    'board.detail.tabProgress': '진행 내용',
    'board.detail.tabChecklist': '체크리스트',
    'board.detail.tabApprovals': '승인/신청',
    'board.detail.tabArtifacts': '산출물',
    'board.detail.tabEval': 'QC/평가',
    'board.detail.tabBilling': '정산',
    'board.detail.tabHistory': '이력',
    'board.detail.descTitle': '설명',
    'board.detail.noDesc': '설명이 없습니다.',
    'board.detail.deadlineLabel': '마감일',
    'board.detail.progressLabel': '진행률',
    'board.detail.updateTitle': '진행 상황 업데이트',
    'board.detail.newProgress': '새 진행률',
    'board.detail.memoLabel': '진행 메모 (작업 내용, 특이사항)',
    'board.detail.memoPlaceholder': '오늘 진행한 작업 내용이나 막힌 부분을 작성해주세요.',
    'board.detail.noAuth': '수정 권한이 없습니다.',
    'board.detail.saveRecord': '기록 저장',
    'board.detail.blockersTitle': '장애 요소 (Blockers)',
    'board.detail.blockersPlaceholder': '작업 진행을 막고 있는 장애물을 입력하세요',
    'board.detail.noBlockers': '등록된 장애 요소가 없습니다.',
    'board.detail.resolvedBtn': '해결 완료',
    'board.detail.resolvedLabel': '해결됨',
    'board.detail.historyTitle': '진행 이력 ({count})',
    'board.detail.noHistory': '기록된 진행 내용이 없습니다.',
    'board.detail.noContent': '내용 없음',
    'board.detail.subTaskTitle': '세부 작업 등록',
    'board.detail.subTaskPlaceholder': '세부 작업 내용',
    'board.detail.noSubTasks': '등록된 세부 작업이 없습니다.',
    'board.detail.noChecklist': '등록된 항목이 없습니다.',
    'board.detail.reqOvertime': '추가 작업시간(야근)<br/>신청',
    'board.detail.reqExt': '마감일 연장<br/>신청',
    'board.detail.reqReplan': '세부 작업일정<br/>조정 요청',
    'board.detail.reqSupport': '인력 지원<br/>요청',
    'board.detail.reqHistoryTitle': '신청 내역',
    'board.detail.reqHistoryDesc': '결재 관리 페이지에서 확인하실 수 있습니다.',
    'board.detail.fileDragLabel': '여기로 파일을 드래그하여 첨부하세요',
    'board.detail.fileDragDesc': '최대 10MB, PDF/JPG/PNG/XLSX/DOCX 지원',
    'board.detail.fileSelectBtn': '파일 선택',
    'board.detail.artifactTitle': '산출물 목록',
    'board.detail.noArtifacts': '등록된 산출물이 없습니다.',
    'board.detail.qcTitle': 'QC 오류 목록',
    'board.detail.qcAdd': '오류 등록',
    'board.detail.noQc': '등록된 QC 오류가 없습니다.',
    'board.detail.qcWeight': '가중치 {weight}%',
    'board.detail.qcReporter': '보고자: {name}',
    'board.detail.qcAppealStat': '이의신청: {status}',
    'board.detail.qcAppealBtn': '이의신청',
    'board.detail.auditPrep': 'AuditLog 통합 이력 뷰 준비 중',
    'board.detail.billingTitle': '외주 정산 (Billing)',
    'board.detail.billingTarget': '외주 진행 업무 (체크 시 비용 정산 대상)',
    'board.detail.billingAmount': '정산 금액 (₩)',
    'board.detail.billingAmountPh': '금액 입력',
    'board.detail.billingStat': '정산 상태',
    'board.detail.billingPending': '대기중',
    'board.detail.billingInvoiced': '청구됨 (인보이스 발행)',
    'board.detail.billingPaid': '지급 완료',

    // P4-C Board & Modal
    'common.save': '저장',
    'common.cancel': '취소',
    'common.add': '추가',
    'common.delete': '삭제',
    'common.close': '닫기',
    'common.confirm': '확인',
    'common.yes': '예',
    'common.no': '아니오',
    'board.column.add': '새 컬럼 추가',
    'board.settings': '보드 설정',
    'board.task.detailTitle': '작업 상세 정보',
    'board.task.subTasks': '세부 작업 등록',
    'board.task.checklist': '체크리스트',
    'board.dispatch.pmTitle': 'PM 배정',
    'board.approval.reviewTitle': '결재 검토',
    'board.revision.reasonLabel': '반려(수정 요청) 사유',
    'board.schedule.requestTitle': '일정 변경 요청',
    'delivery.postWork.title': '사후 추가업무 요청',
    'evaluation.project.title': '프로젝트 성과 평가',
    'evaluation.qc.issueTitle': 'QC 오류 등록',
    'schedule.leave.title': '휴가/개인 일정 등록',
    'alert.requireTitleReason': '제목과 사유를 입력해주세요.',
    'alert.postWorkSubmitted': '사후 추가업무 요청이 제출되었습니다. PM 승인을 대기합니다.',
    'alert.evalSaved': '프로젝트 종합 의견이 저장되었습니다.',
    'alert.requireTitleDesc': '오류 제목과 설명을 입력해주세요.',
    'alert.qcIssueSubmitted': 'QC 오류가 등록되었습니다.',
    'alert.requireFields': '필수 항목을 입력해주세요.',
    'alert.leaveSubmitted': '일정 등록 및 결재 요청이 완료되었습니다.',
    'evaluation.eval.pmOpinionTitle': 'PM 종합 의견 작성 (평가 참고용)',
    'evaluation.eval.pmOpinionDesc': '이 의견은 직접적인 평가 점수에 반영되지 않으나, QC팀이 프로젝트 상황을 이해하고 오류 내용 및 가중치를 검토할 수 있도록 돕기 위한 참고 자료입니다.',
    'evaluation.eval.summaryLabel': '프로젝트 종합 요약',
    'evaluation.eval.summaryPlaceholder': '프로젝트 전반적인 진행 여건 및 특수성을 요약해주세요.',
    'evaluation.eval.scheduleLabel': '일정 난이도 의견',
    'evaluation.eval.schedulePlaceholder': '촉박한 납기, 잦은 일정 변경 등 일정 관련 특이사항을 적어주세요.',
    'evaluation.eval.scopeLabel': '범위/난이도 의견',
    'evaluation.eval.scopePlaceholder': '고난이도 작업, 잦은 설계 변경 등 작업 난이도 관련 특이사항을 적어주세요.',
    'evaluation.eval.saveOpinion': '의견 저장',
    'delivery.postWork.titleLabel': '제목',
    'delivery.postWork.titlePlaceholder': '추가 업무 제목',
    'delivery.postWork.reasonLabel': '사유',
    'delivery.postWork.reasonSelect': '사유 선택',
    'delivery.postWork.reasonClient': '고객사 추가 요청',
    'delivery.postWork.reasonDefect': '납품 후 결함 수정',
    'delivery.postWork.reasonScope': '요구사항 변경 반영',
    'delivery.postWork.reasonEtc': '기타',
    'delivery.postWork.detailLabel': '상세 내용',
    'delivery.postWork.detailPlaceholder': '상세 내용을 입력하세요',
    'delivery.postWork.timeLabel': '예상 소요 시간',
    'delivery.postWork.timeUnit': '시간',
    'delivery.postWork.changeDate': '납품일 변경이 필요한가요?',
    'delivery.postWork.newDate': '새로운 제안 납품일',
    'delivery.postWork.submit': '요청 제출',
    'evaluation.qc.stage': '발견 단계',
    'evaluation.qc.stage1': '제출자료 검토사항',
    'evaluation.qc.stage2': '최종자료 검토사항',
    'evaluation.qc.stage3': '납품전 검토',
    'evaluation.qc.stage4': '납품후 수정',
    'evaluation.qc.titleLabel': '오류 제목',
    'evaluation.qc.titlePlaceholder': '예: 치수 표기 누락',
    'evaluation.qc.descLabel': '오류 설명',
    'evaluation.qc.descPlaceholder': '상세한 오류 내용을 적어주세요.',
    'evaluation.qc.severity': '심각도',
    'evaluation.qc.sevLow': 'LOW (경미)',
    'evaluation.qc.sevMedium': 'MEDIUM (보통)',
    'evaluation.qc.sevHigh': 'HIGH (심각)',
    'evaluation.qc.sevCritical': 'CRITICAL (매우 심각)',
    'evaluation.qc.weight': 'QC 가중치 (%)',
    'evaluation.qc.weight100': '100% (1건당 1개 오류 반영)',
    'evaluation.qc.weight50': '50% (2건당 1개 오류 반영)',
    'evaluation.qc.weight25': '25% (4건당 1개 오류 반영)',
    'evaluation.qc.weight10': '10% (10건당 1개 오류 반영)',
    'evaluation.qc.submit': '오류 확정 및 등록',
    'schedule.leave.type': '일정 구분',
    'schedule.leave.typeOff': '휴가 (연차/반차)',
    'schedule.leave.typeEtc': '기타 개인 일정 (외근/교육 등)',
    'schedule.leave.titleLabel': '제목',
    'schedule.leave.titlePlaceholder': '예: 여름 휴가, 오후 반차',
    'schedule.leave.date': '날짜',
    'schedule.leave.reason': '상세 사유',
    'schedule.leave.reasonPlaceholder': '상세 사유를 입력하세요 (선택)',
    'schedule.leave.submit': '결재 요청',

    // Header & Sidebar
    dashboard: '대시보드',
    projectBoard: '통합 프로젝트 보드',
    projectIntake: '수주/개발 관리',
    approvals: '결재/수정 내역',
    conflicts: '일정 충돌 관리',
    schedules: '통합 일정표',
    notifications: '알림 센터',
    settings: '운영 설정',
    myTasks: '내 업무',
    evaluation: '성과 평가',

    // Board Columns
    preWork: '착수 전',
    inProgress: '진행 중',
    completed: '완료',
    revision: '수정',

    // Board Tabs
    devTeamWork: '개발팀 작업',
    externalProject: '외부 수주 프로젝트',

    // Board Time Badges
    goal: '목표',
    delivery: '납품',
    overdue: '🚨 {label}일 경과',
    dueIn: '{time} 전',
    unset: '미정',

    // Intake
    newProjectReg: '신규 프로젝트 등록',
    orderProjectManagement: '수주 프로젝트 관리',
    devTaskListManagement: '개발팀 업무 리스트 관리',

    // Settings
    translationSettings: '번역 설정',
    workspaceSettings: '운영 환경 설정',
    personnelManagement: '사원 관리',
    bulkEdit: '일괄 마감 (Danger)',
    dataQuality: '데이터 품질 검사기',
    importPreview: '가져오기 (JSON)',
    permissions: '권한 정책 설정',

    // Translation UI Warnings
    apiWarning: '주의: 업무상 민감한 내용이 무료 외부 API 서버로 전송될 수 있습니다. 정식 운영 시에는 자체 서버 구축을 권장합니다.',
    fallbackManual: '무료 번역 한도 초과 / 수동 번역 필요',

    // Modal Tabs
    overview: '개요',

    // P4-A Added Keys
    'header.role.superAdmin': '최고관리자',
    'header.role.systemAdmin': '시스템관리자',
    'header.role.deptManager': '부서장',
    'header.role.pm': 'PM',
    'header.role.worker': '작업자',
    'header.dept.hq': '본사',
    'header.dept.none': '소속 없음',
    'header.loginRequired': '로그인 필요',
    'header.mode.real': '실사용 모드',
    'header.mode.validation': '운영 검증',
    'header.data.prefix': '데이터: ',
    'header.data.json': 'JSON 운영',
    'header.data.demo': 'Demo Seed',
    'header.data.excel': 'Excel 임포트',
    'header.data.empty': '비어 있음',
    'header.nav.approvals': '결재함',
    'header.nav.evaluation': '성과 평가',

    'notification.title': '알림',
    'notification.readAll': '모두 읽음',
    'notification.empty': '새로운 알림이 없습니다.',
    'notification.viewAll': '알림 센터 전체보기',

    'settings.title': '설정 및 내 정보',
    'settings.loginRequired': '로그인이 필요합니다.',
    'settings.section.basicInfo': '기본 정보',
    'settings.field.name': '이름',
    'settings.field.role': '권한 (Role)',
    'settings.field.department': '부서',
    'settings.field.emailMock': '이메일 (Mock)',
    'settings.section.appSettings': '앱 설정',
    'settings.theme.dark': '다크 모드',
    'settings.emailAlerts': '이메일 알림 수신',
    'settings.note.backend': '* 실제 환경 설정은 백엔드 연동 이후 반영됩니다.',

    'common.progress': '진행률',

    // P4-B Added Keys
    'dashboard.loading': 'Loading...',
    'dashboard.title': '통합 대시보드',
    'dashboard.subtitle': '기준 전체 업무 현황',
    'dashboard.filter.allMonths': '전체 월 조회',
    'common.yearMonth': '{year}년 {month}월',
    'dashboard.actions.importJson': 'JSON 불러오기',
    'dashboard.actions.exportJson': 'JSON 내보내기',

    'dashboard.metric.inProgressProject': '진행 중 프로젝트',
    'dashboard.metric.inProgressDesc': '이번 달 전체 진행 건',
    'dashboard.metric.overdueProject': '납품 경과 프로젝트',
    'dashboard.metric.overdueDesc': '납품일 1주일 이내 및 경과',
    'dashboard.metric.myTasks': '내 작업',
    'dashboard.metric.myTasksDesc': '할당된 전체 업무',
    'dashboard.metric.completedTasks': '완료된 작업',
    'dashboard.metric.completedTasksDesc': '승인 완료된 업무',
    'dashboard.metric.pending': '승인 대기',
    'dashboard.metric.pendingDesc': 'PM 검토 대기 건',
    'dashboard.metric.revision': '수정 요청 (반려)',
    'dashboard.metric.revisionDesc': '재작업이 필요한 건',

    'dashboard.sa.pendingApproval': '결재/승인 대기',
    'dashboard.sa.pendingApprovalDesc': '승인 대기 중인 문서',
    'dashboard.sa.delayedTask': '지연/충돌 업무',
    'dashboard.sa.delayedTaskDesc': '마감일 경과 또는 미처리 건',
    'dashboard.sa.projectSummary': '월별 프로젝트 요약',
    'dashboard.sa.emptyProject': '아직 표시할 프로젝트가 없습니다.',
    'dashboard.sa.emptyProjectDesc': 'JSON 데이터를 불러오거나 새 프로젝트를 등록해 주세요.',

    'dashboard.dm.deptProject': '부서 전체 프로젝트',
    'dashboard.dm.deptProjectDesc': '부서 내 진행 중인 건',
    'dashboard.dm.pendingApproval': '부서원 결재 대기',
    'dashboard.dm.pendingApprovalDesc': '부서장 승인 필요 문서',
    'dashboard.dm.emptyProject': '부서 내 진행 중인 프로젝트가 없습니다.',
    'dashboard.dm.emptyProjectDesc': '프로젝트 보드에서 새 업무를 할당받거나 생성하세요.',

    'dashboard.pm.myProject': '담당 프로젝트',
    'dashboard.pm.myProjectDesc': 'PM으로 배정된 프로젝트',
    'dashboard.pm.pendingReview': '검토 대기 업무',
    'dashboard.pm.pendingReviewDesc': '팀원 작업물 검토 대기 건',
    'dashboard.pm.emptyProject': '담당 중인 프로젝트가 없습니다.',
    'dashboard.pm.emptyProjectDesc': 'PM으로 배정된 프로젝트 내역이 이곳에 표시됩니다.',

    'dashboard.table.deliveryExpected': '납품 예정일',
    'dashboard.table.targetExpected': '목표 예정일',

    'dashboard.section.recentTasks': '최근 할당된 작업',
    'dashboard.empty.noTasks': '할당된 작업이 없습니다.',
    'dashboard.empty.noTasksDesc': 'PM이 업무를 할당하면 이곳에 표시됩니다.',
    'dashboard.table.taskName': '작업명',
    'dashboard.table.project': '프로젝트',
    'dashboard.table.projectName': '프로젝트명',
    'dashboard.table.category': '구분',
    'dashboard.table.progress': '진척도',
    'dashboard.table.status': '상태',
    'dashboard.table.dueDate': '마감일',

    'dashboard.projectType.order': '수주',
    'dashboard.projectType.internal': '내부개발',
    'common.unset': '미정',
    'dashboard.status.pending': '승인 대기',
    'dashboard.status.rejected': '반려',

    'dashboard.widget.workManagement': '업무관리',
    'dashboard.work.inProgress': '진행중',
    'dashboard.work.qcPending': 'QC대기',
    'dashboard.work.upcomingDelivery': '납품임박',
    'dashboard.work.empty': '해당하는 프로젝트가 없습니다.',
    'dashboard.work.deptPm': '부서/PM',
    'dashboard.work.targetDate': '완료예정일',
    'dashboard.work.deliveryDate': '납품일',
    'dashboard.work.progress': '진척도',
    'dashboard.work.deferredNote': '* 회의록/전화/메일/납품차수 등 상세 원본 기능은 이번 위젯에 직접 구현되지 않았습니다 (Deferred).',

    'dashboard.widget.managementSupport': '경영지원',
    'dashboard.support.tabs.notice': '공지사항',
    'dashboard.support.tabs.hr': '조직/인사',
    'dashboard.support.tabs.form': '양식함',
    'dashboard.support.noNotice': '등록된 공지사항이 없습니다.',
    'dashboard.support.important': '필독',
    'dashboard.support.hrSummary': '인사 변동 요약 (이번 달)',
    'dashboard.support.newHires': '신규 입사',
    'dashboard.support.resigned': '퇴사',
    'dashboard.support.deptStatus': '부서별 인원 현황',
    'dashboard.support.noDeptData': '부서 인원 데이터가 없습니다.',
    'dashboard.support.form.vacation': '휴가 신청서 양식',
    'dashboard.support.form.overtime': '초과근무 신청서 양식',
    'dashboard.support.download': '다운로드',
    'dashboard.support.peopleUnit': '명',
  },
  vi: {
    // P4-C Modals Extended
    'board.approval.approvedAlert': 'Đã xử lý phê duyệt.',
    'board.approval.rejectReasonRequired': 'Phải nhập lý do khi từ chối.',
    'board.approval.rejectedAlert': 'Đã xử lý từ chối.',
    'board.approval.title': 'Xử lý phê duyệt',
    'board.approval.reqTitle': 'Tiêu đề yêu cầu',
    'board.approval.detailReason': 'Lý do chi tiết',
    'board.approval.hopeDate': 'Lịch trình mong muốn',
    'board.approval.reviewComment': 'Ý kiến xem xét (Tùy chọn)',
    'board.approval.reviewCommentPlaceholder': 'Vui lòng nhập ý kiến bổ sung về việc phê duyệt/từ chối.',
    'board.approval.reject': 'Từ chối',
    'board.approval.approve': 'Phê duyệt',
    'board.status.waiting': 'Chờ bắt đầu công việc',
    'board.status.qcPmStart': 'QC/PM bắt đầu công việc',
    'board.status.inProgress': 'Đang tiến hành',
    'board.status.pmReview': 'PM xem xét',
    'board.status.qcReview': 'QC xem xét',
    'board.status.done': 'Hoàn thành',
    'board.column.todo': '📥 Nhận đơn/Chờ',
    'board.column.review': '🔎 QC/Kiểm tra',
    'board.column.done': '✅ Hoàn thành',
    'board.deadline.1week': '🔴 1 tuần trước giao hàng',
    'board.deadline.2weeks': '🟠 2 tuần trước giao hàng',
    'board.deadline.1month': '🔵 1 tháng trước giao hàng',
    'board.deadline.unset': '⚪ Chưa quyết định',
    'board.assignee.unassigned': 'Chưa phân công',
    'board.alert.noAssign': 'Nhân viên không thể phân công công việc cho người khác.',
    'board.alert.onlyOwn': 'Chỉ có thể di chuyển thẻ công việc của chính mình.',
    'board.alert.noSkip': 'Không thể bỏ qua bước quy trình để di chuyển.',
    'board.column.avg': 'Trung bình',
    'board.column.delayed': 'Trễ',
    'board.column.urgent': 'Khẩn cấp',
    'board.column.pending': 'Chờ',
    'board.dispatch.alertNoLang': 'Không thể nhận dạng ngôn ngữ. Vui lòng nhập rõ ràng tiếng Hàn hoặc tiếng Việt.',
    'board.dispatch.translating': 'Đang dịch...',
    'board.dispatch.alertNoTask': 'Phải thêm ít nhất 1 công việc.',
    'board.dispatch.alertMissingFields': 'Phải nhập tiêu đề, người phụ trách, ngày bắt đầu/kết thúc, thời gian dự kiến cho tất cả công việc.',
    'board.dispatch.alertInvalidDate': 'Ngày bắt đầu không thể muộn hơn ngày kết thúc.',
    'board.dispatch.alertDeadlineExceeded': 'Ngày kết thúc của một số công việc vượt quá thời hạn cuối cùng của dự án ({projectLimit}). Bạn có muốn tiếp tục?',
    'board.dispatch.modalTitle': 'Phân công công việc của PM (Task Dispatch)',
    'board.dispatch.prevRejectReason': 'Lý do từ chối trước đó',
    'board.dispatch.noReason': 'Không có lý do',
    'board.dispatch.extOrder': 'Đơn hàng bên ngoài',
    'board.dispatch.internalDev': 'Dự án nội bộ',
    'board.dispatch.pmInCharge': 'PM phụ trách:',
    'board.dispatch.finalDeadline': 'Thời hạn cuối cùng:',
    'board.dispatch.taskListTitle': 'Danh sách tạo công việc chi tiết (Task)',
    'board.dispatch.addTask': 'Thêm công việc',
    'board.dispatch.taskName': 'Tên công việc *',
    'board.dispatch.taskNamePlaceholder': 'Nhập tên công việc',
    'board.dispatch.autoTranslate': 'Dịch tự động',
    'board.dispatch.assignee': 'Người phụ trách *',
    'board.dispatch.assigneeSelect': 'Chọn người phụ trách',
    'board.dispatch.priority': 'Độ ưu tiên',
    'board.dispatch.priUrgent': 'Khẩn cấp',
    'board.dispatch.priHigh': 'Cao',
    'board.dispatch.priNormal': 'Bình thường',
    'board.dispatch.priLow': 'Thấp',
    'board.dispatch.estTime': 'Thời gian dự kiến (giờ) *',
    'board.dispatch.startDate': 'Ngày bắt đầu dự kiến *',
    'board.dispatch.endDate': 'Ngày kết thúc *',
    'board.dispatch.warnOffDays': 'Lịch trình có bao gồm ngày nghỉ phép (OFF) của nhân viên.',
    'board.dispatch.warnOverload': 'Tải trọng trung bình dự kiến hàng ngày bao gồm cả công việc hiện tại vượt quá 8 giờ ({avgDaily}h/ngày).',
    'board.dispatch.langKoDetected': 'Phát hiện tiếng Hàn · Sẽ dịch sang VI',
    'board.dispatch.langViDetected': 'Phát hiện tiếng Việt · Sẽ dịch sang KO',
    'board.dispatch.langUnknown': 'Không xác định',
    'board.dispatch.inputLanguage': 'Ngôn ngữ nhập:',
    'board.dispatch.transFailed': '(Dịch thất bại)',
    'board.dispatch.limitExceeded': 'Vượt quá hạn mức',
    'board.dispatch.submitRetry': 'Yêu cầu lại lịch trình công việc',
    'board.dispatch.submitNew': 'Phân công công việc và chuyển sang đang tiến hành',
    'board.process.noReason': 'Chưa ghi lý do.',
    'board.process.alertSelectManager': 'Vui lòng chọn người có quyền phê duyệt (Quản lý).',
    'board.process.confirmSubmit': 'Bạn có muốn yêu cầu phê duyệt không?',
    'board.process.reqTitle': '[Yêu cầu phê duyệt quy trình] {title}',
    'board.process.reqReason': 'Yêu cầu phê duyệt lịch trình chi tiết dựa trên mẫu quy trình',
    'board.process.alertRequested': 'Đã yêu cầu quản lý cấp trung phê duyệt.',
    'board.process.noTemplateTitle': 'Chưa áp dụng mẫu quy trình',
    'board.process.noTemplateDesc': 'Không có mẫu quy trình nào được áp dụng cho công việc này. Vui lòng áp dụng mẫu để lập kế hoạch chi tiết.',
    'board.process.selectTemplate': 'Chọn mẫu...',
    'board.process.apply': 'Áp dụng',
    'board.process.rejected': 'Bị từ chối phê duyệt',
    'board.process.rewrite': 'Chỉnh sửa lại lịch trình (Bản nháp)',
    'board.process.scheduleChart': 'Bảng lịch trình quy trình (Đang tiến hành)',
    'board.process.status': 'Trạng thái:',
    'board.process.selectApprover': 'Chọn người phê duyệt...',
    'board.process.reqApproval': 'Yêu cầu phê duyệt',
    'board.process.defaultAssign': 'Phân công mặc định:',
    'board.process.assigneeLabel': 'Người phụ trách',
    'board.process.select': 'Chọn...',
    'board.process.startLabel': 'Ngày bắt đầu',
    'board.process.endLabel': 'Ngày kết thúc',
    'board.process.estLabel': 'Dự kiến (h)',
    'board.process.detailPlaceholder': 'Chỉ thị chi tiết...',
    'board.project.noProject': 'Không có dự án',
    'board.part.noPart': 'Không có phần công việc được phân công.',
    'board.part.dispatchBtn': 'Phân công công việc chi tiết và phần việc',
    'board.part.confirmApprove': 'Bạn có chắc chắn muốn phê duyệt kế hoạch lịch trình đã lập và phản ánh thành lịch trình chính thức không?',
    'board.part.promptReject': 'Vui lòng nhập lý do từ chối:',
    'board.part.reqManagerReview': 'Yêu cầu Trưởng phòng (MANAGER) kiểm tra',
    'board.part.waitApprovalDesc': 'Đang chờ phê duyệt lịch trình chi tiết do PM lập.',
    'board.part.rejectSchedule': 'Từ chối lịch trình',
    'board.part.approveSchedule': 'Phê duyệt và phản ánh lịch trình',
    'board.part.previewTitle': 'Xem trước lịch trình chờ phê duyệt & Phân tích tải theo nhân viên',
    'board.part.conflictCountAlert': 'Phát hiện trùng lặp lịch trình (nghỉ phép hoặc quá tải) trong {conflictCount} công việc. Vui lòng chú ý khi phê duyệt.',
    'board.part.thTask': 'Tên công việc',
    'board.part.thAssignee': 'Người phụ trách',
    'board.part.thPeriod': 'Khoảng thời gian',
    'board.part.thEst': 'Dự kiến',
    'board.part.thConflict': 'Phân tích xung đột',
    'board.part.conflictOff': 'Trùng lịch nghỉ',
    'board.part.conflictOverload': 'Quá tải ({avgDaily}h/ngày)',
    'board.part.conflictOk': 'Bình thường',
    'board.part.rejectedAlert': 'Lịch trình bạn lập đã bị quản lý từ chối. Cần chỉnh sửa và yêu cầu lại.',
    'board.part.rewriteRetry': 'Chỉnh sửa và yêu cầu lại lịch trình',
    'board.part.taskCount': '{count} việc',
    'board.part.participantCount': 'Tham gia {count} người',
    'board.part.progressPercent': 'Tiến độ {percent}%',
    'board.part.statusPending': 'Chờ phê duyệt',
    'board.part.statusRejected': 'Bị từ chối',
    'board.part.taskDone': 'Đã hoàn thành',
    'board.part.noTasks': 'Không có thẻ công việc nào được đăng ký.',
    'board.summary.sourceOrder': 'Nhận thầu',
    'board.summary.sourceInternal': 'Phát triển nội bộ',
    'board.summary.pmUnset': 'Chưa chỉ định người phụ trách',
    'board.summary.targetTarget': 'Mục tiêu {date}',
    'board.summary.targetDelivery': 'Giao hàng {date}',
    'board.summary.progress': 'Tiến độ',
    'board.summary.pendingTasks': 'Còn lại {count} việc',
    'board.summary.addRequests': 'Công việc thêm {count} việc',
    'board.summary.revisions': 'Yêu cầu sửa {count} việc',
    'board.summary.finalApprove': 'Phê duyệt hoàn thành cuối cùng',
    'board.revision.alertReqFields': 'Vui lòng nhập tiêu đề và nội dung chi tiết.',
    'board.revision.alertSubmitted': 'Yêu cầu chỉnh sửa (Revision) đã được tiếp nhận.',
    'board.revision.title': 'Yêu cầu chỉnh sửa (Revision)',
    'board.revision.targetProject': 'Dự án mục tiêu',
    'board.revision.reqTitleLabel': 'Tiêu đề yêu cầu chỉnh sửa *',
    'board.revision.reqTitlePlaceholder': 'VD) Thay đổi logo trang đăng nhập',
    'board.revision.reqDescLabel': 'Nội dung chi tiết yêu cầu chỉnh sửa *',
    'board.revision.reqDescPlaceholder': 'Vui lòng nhập nội dung chỉnh sửa cụ thể do khách hàng yêu cầu.',
    'board.revision.submit': 'Đăng ký yêu cầu',
    'board.schedReq.extTitle': 'Yêu cầu gia hạn lịch trình',
    'board.schedReq.overtimeTitle': 'Yêu cầu thời gian làm việc thêm (Làm thêm giờ)',
    'board.schedReq.supportTitle': 'Yêu cầu hỗ trợ nhân lực',
    'board.schedReq.replanTitle': 'Yêu cầu điều chỉnh lịch trình công việc chi tiết',
    'board.schedReq.defaultTitle': 'Đăng ký',
    'board.schedReq.alertReqReason': 'Vui lòng nhập lý do yêu cầu.',
    'board.schedReq.alertSubmitted': 'Yêu cầu đã hoàn tất.',
    'board.schedReq.targetTask': 'Công việc mục tiêu',
    'board.schedReq.currentSched': 'Lịch trình hiện tại',
    'board.schedReq.hopeStart': 'Ngày bắt đầu mong muốn',
    'board.schedReq.hopeEnd': 'Ngày kết thúc mong muốn',
    'board.schedReq.reasonLabel': 'Lý do yêu cầu *',
    'board.schedReq.reasonPlaceholder': 'Vui lòng nhập lý do cụ thể.',
    'board.schedReq.submit': 'Gửi',
    'board.card.autoTransLabel': '[Dịch tự động {lang}] {text}',
    'board.card.orgTextLabel': '[Văn bản gốc {lang}] {text}',
    'board.card.noTransLabel': '(Không thể dịch sang {lang})',
    'board.card.postWork': 'Công việc thêm',
    'board.card.delayed': 'Trễ',
    'board.card.pendingApprove': 'Chờ phê duyệt',
    'board.card.needReview': 'Cần xem xét',
    'board.card.approvedTrans': 'Đã duyệt dịch',
    'board.card.billingLabel': 'Chi phí thuê ngoài: {amount} KRW',
    'board.card.outsourced': 'Thuê ngoài',
    'board.card.tooltipAssignee': 'Người phụ trách',
    'board.card.tooltipDeadline': 'Hạn chót',
    'board.detail.alertProgressNote': 'Tiến độ thay đổi đáng kể. Vui lòng để lại ghi chú chi tiết về tiến độ (ít nhất 5 ký tự).',
    'board.detail.alertNoteSaved': 'Nội dung tiến độ đã được ghi lại.',
    'board.detail.alertStartInvalid': 'Ngày bắt đầu công việc chi tiết không thể sớm hơn ngày bắt đầu của thẻ.',
    'board.detail.alertEndInvalid': 'Ngày kết thúc công việc chi tiết không thể muộn hơn ngày kết thúc của thẻ.',
    'board.detail.alertFileLarge': 'Dung lượng của \'{name}\' vượt quá 10MB.',
    'board.detail.alertFileInvalid': '\'{name}\' là định dạng tệp không được hỗ trợ. (Chỉ cho phép PDF, JPG, PNG, XLSX, DOCX)',
    'board.detail.promptAppeal': 'Vui lòng viết cụ thể lý do khiếu nại về kết quả QC (trọng số, v.v.).',
    'board.detail.alertAppealSubmitted': 'Khiếu nại đã được tiếp nhận. Quản trị viên sẽ xem xét và quyết định có điều chỉnh lại hay không.',
    'board.detail.tabOverview': 'Tổng quan',
    'board.detail.tabProcess': 'Mẫu quy trình',
    'board.detail.tabSegments': 'Chi tiết công việc',
    'board.detail.tabProgress': 'Nội dung tiến độ',
    'board.detail.tabChecklist': 'Danh sách kiểm tra',
    'board.detail.tabApprovals': 'Phê duyệt/Yêu cầu',
    'board.detail.tabArtifacts': 'Sản phẩm',
    'board.detail.tabEval': 'QC/Đánh giá',
    'board.detail.tabBilling': 'Thanh toán',
    'board.detail.tabHistory': 'Lịch sử',
    'board.detail.descTitle': 'Mô tả',
    'board.detail.noDesc': 'Không có mô tả.',
    'board.detail.deadlineLabel': 'Hạn chót',
    'board.detail.progressLabel': 'Tiến độ',
    'board.detail.updateTitle': 'Cập nhật tình hình tiến độ',
    'board.detail.newProgress': 'Tiến độ mới',
    'board.detail.memoLabel': 'Ghi chú tiến độ (Nội dung công việc, điểm đặc biệt)',
    'board.detail.memoPlaceholder': 'Vui lòng viết nội dung công việc đã thực hiện hôm nay hoặc các phần bị vướng mắc.',
    'board.detail.noAuth': 'Không có quyền chỉnh sửa.',
    'board.detail.saveRecord': 'Lưu ghi chép',
    'board.detail.blockersTitle': 'Yếu tố cản trở (Blockers)',
    'board.detail.blockersPlaceholder': 'Nhập chướng ngại vật đang cản trở tiến độ công việc',
    'board.detail.noBlockers': 'Không có yếu tố cản trở nào được đăng ký.',
    'board.detail.resolvedBtn': 'Đã giải quyết',
    'board.detail.resolvedLabel': 'Đã giải quyết',
    'board.detail.historyTitle': 'Lịch sử tiến độ ({count})',
    'board.detail.noHistory': 'Không có nội dung tiến độ nào được ghi lại.',
    'board.detail.noContent': 'Không có nội dung',
    'board.detail.subTaskTitle': 'Đăng ký công việc chi tiết',
    'board.detail.subTaskPlaceholder': 'Nội dung công việc chi tiết',
    'board.detail.noSubTasks': 'Không có công việc chi tiết nào được đăng ký.',
    'board.detail.noChecklist': 'Không có mục nào được đăng ký.',
    'board.detail.reqOvertime': 'Yêu cầu<br/>làm thêm giờ',
    'board.detail.reqExt': 'Yêu cầu<br/>gia hạn hạn chót',
    'board.detail.reqReplan': 'Yêu cầu<br/>điều chỉnh lịch',
    'board.detail.reqSupport': 'Yêu cầu<br/>hỗ trợ nhân lực',
    'board.detail.reqHistoryTitle': 'Chi tiết yêu cầu',
    'board.detail.reqHistoryDesc': 'Bạn có thể kiểm tra trên trang quản lý phê duyệt.',
    'board.detail.fileDragLabel': 'Kéo tệp vào đây để đính kèm',
    'board.detail.fileDragDesc': 'Tối đa 10MB, hỗ trợ PDF/JPG/PNG/XLSX/DOCX',
    'board.detail.fileSelectBtn': 'Chọn tệp',
    'board.detail.artifactTitle': 'Danh sách sản phẩm',
    'board.detail.noArtifacts': 'Không có sản phẩm nào được đăng ký.',
    'board.detail.qcTitle': 'Danh sách lỗi QC',
    'board.detail.qcAdd': 'Đăng ký lỗi',
    'board.detail.noQc': 'Không có lỗi QC nào được đăng ký.',
    'board.detail.qcWeight': 'Trọng số {weight}%',
    'board.detail.qcReporter': 'Người báo cáo: {name}',
    'board.detail.qcAppealStat': 'Khiếu nại: {status}',
    'board.detail.qcAppealBtn': 'Khiếu nại',
    'board.detail.auditPrep': 'Đang chuẩn bị chế độ xem lịch sử tích hợp AuditLog',
    'board.detail.billingTitle': 'Thanh toán thuê ngoài (Billing)',
    'board.detail.billingTarget': 'Công việc thuê ngoài (Đánh dấu để thanh toán chi phí)',
    'board.detail.billingAmount': 'Số tiền thanh toán (₩)',
    'board.detail.billingAmountPh': 'Nhập số tiền',
    'board.detail.billingStat': 'Trạng thái thanh toán',
    'board.detail.billingPending': 'Đang chờ',
    'board.detail.billingInvoiced': 'Đã yêu cầu (Đã xuất hóa đơn)',
    'board.detail.billingPaid': 'Đã thanh toán',

    // P4-C Board & Modal
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.add': 'Thêm',
    'common.delete': 'Xóa',
    'common.close': 'Đóng',
    'common.confirm': 'Xác nhận',
    'common.yes': 'Có',
    'common.no': 'Không',
    'board.column.add': 'Thêm cột mới',
    'board.settings': 'Cài đặt bảng',
    'board.task.detailTitle': 'Thông tin chi tiết công việc',
    'board.task.subTasks': 'Đăng ký công việc chi tiết',
    'board.task.checklist': 'Danh sách kiểm tra',
    'board.dispatch.pmTitle': 'Phân công PM',
    'board.approval.reviewTitle': 'Xem xét phê duyệt',
    'board.revision.reasonLabel': 'Lý do từ chối (Yêu cầu chỉnh sửa)',
    'board.schedule.requestTitle': 'Yêu cầu thay đổi lịch trình',
    'delivery.postWork.title': 'Yêu cầu công việc bổ sung sau giao hàng',
    'evaluation.project.title': 'Đánh giá hiệu quả dự án',
    'evaluation.qc.issueTitle': 'Đăng ký lỗi QC',
    'schedule.leave.title': 'Đăng ký nghỉ phép/lịch trình cá nhân',
    'alert.requireTitleReason': 'Vui lòng nhập tiêu đề và lý do.',
    'alert.postWorkSubmitted': 'Yêu cầu công việc bổ sung sau giao hàng đã được gửi. Đang chờ PM phê duyệt.',
    'alert.evalSaved': 'Ý kiến tổng hợp dự án đã được lưu.',
    'alert.requireTitleDesc': 'Vui lòng nhập tiêu đề và mô tả lỗi.',
    'alert.qcIssueSubmitted': 'Lỗi QC đã được đăng ký.',
    'alert.requireFields': 'Vui lòng nhập các trường bắt buộc.',
    'alert.leaveSubmitted': 'Đăng ký lịch trình và yêu cầu phê duyệt đã hoàn tất.',
    'evaluation.eval.pmOpinionTitle': 'Viết ý kiến tổng hợp của PM (Dành cho tham khảo đánh giá)',
    'evaluation.eval.pmOpinionDesc': 'Ý kiến này không phản ánh trực tiếp vào điểm đánh giá, nhưng là tài liệu tham khảo để nhóm QC có thể hiểu và xem xét tình hình dự án.',
    'evaluation.eval.summaryLabel': 'Tóm tắt tổng hợp dự án',
    'evaluation.eval.summaryPlaceholder': 'Vui lòng tóm tắt các điều kiện tiến hành và đặc thù chung của dự án.',
    'evaluation.eval.scheduleLabel': 'Ý kiến về độ khó lịch trình',
    'evaluation.eval.schedulePlaceholder': 'Vui lòng ghi lại các đặc thù liên quan đến lịch trình như thời hạn giao hàng gấp rút, lịch trình thường xuyên thay đổi v.v.',
    'evaluation.eval.scopeLabel': 'Ý kiến về phạm vi/độ khó',
    'evaluation.eval.scopePlaceholder': 'Vui lòng ghi lại các đặc thù liên quan đến độ khó công việc như công việc độ khó cao, thiết kế thường xuyên thay đổi v.v.',
    'evaluation.eval.saveOpinion': 'Lưu ý kiến',
    'delivery.postWork.titleLabel': 'Tiêu đề',
    'delivery.postWork.titlePlaceholder': 'Tiêu đề công việc bổ sung',
    'delivery.postWork.reasonLabel': 'Lý do',
    'delivery.postWork.reasonSelect': 'Chọn lý do',
    'delivery.postWork.reasonClient': 'Yêu cầu bổ sung từ khách hàng',
    'delivery.postWork.reasonDefect': 'Sửa lỗi sau khi giao hàng',
    'delivery.postWork.reasonScope': 'Phản ánh thay đổi yêu cầu',
    'delivery.postWork.reasonEtc': 'Khác',
    'delivery.postWork.detailLabel': 'Nội dung chi tiết',
    'delivery.postWork.detailPlaceholder': 'Vui lòng nhập nội dung chi tiết',
    'delivery.postWork.timeLabel': 'Thời gian dự kiến',
    'delivery.postWork.timeUnit': 'Giờ',
    'delivery.postWork.changeDate': 'Cần thay đổi ngày giao hàng?',
    'delivery.postWork.newDate': 'Ngày giao hàng đề xuất mới',
    'delivery.postWork.submit': 'Gửi yêu cầu',
    'evaluation.qc.stage': 'Giai đoạn phát hiện',
    'evaluation.qc.stage1': 'Hạng mục kiểm tra tài liệu đệ trình',
    'evaluation.qc.stage2': 'Hạng mục kiểm tra tài liệu cuối cùng',
    'evaluation.qc.stage3': 'Kiểm tra trước khi giao hàng',
    'evaluation.qc.stage4': 'Chỉnh sửa sau khi giao hàng',
    'evaluation.qc.titleLabel': 'Tiêu đề lỗi',
    'evaluation.qc.titlePlaceholder': 'VD: Thiếu ghi chú kích thước',
    'evaluation.qc.descLabel': 'Mô tả lỗi',
    'evaluation.qc.descPlaceholder': 'Vui lòng nhập nội dung lỗi chi tiết.',
    'evaluation.qc.severity': 'Mức độ nghiêm trọng',
    'evaluation.qc.sevLow': 'LOW (Nhẹ)',
    'evaluation.qc.sevMedium': 'MEDIUM (Trung bình)',
    'evaluation.qc.sevHigh': 'HIGH (Nghiêm trọng)',
    'evaluation.qc.sevCritical': 'CRITICAL (Rất nghiêm trọng)',
    'evaluation.qc.weight': 'Trọng số QC (%)',
    'evaluation.qc.weight100': '100% (Phản ánh 1 lỗi mỗi 1 trường hợp)',
    'evaluation.qc.weight50': '50% (Phản ánh 1 lỗi mỗi 2 trường hợp)',
    'evaluation.qc.weight25': '25% (Phản ánh 1 lỗi mỗi 4 trường hợp)',
    'evaluation.qc.weight10': '10% (Phản ánh 1 lỗi mỗi 10 trường hợp)',
    'evaluation.qc.submit': 'Xác nhận và đăng ký lỗi',
    'schedule.leave.type': 'Phân loại lịch trình',
    'schedule.leave.typeOff': 'Nghỉ phép (Ngày/Nửa ngày)',
    'schedule.leave.typeEtc': 'Lịch trình cá nhân khác (Công tác/Đào tạo v.v.)',
    'schedule.leave.titleLabel': 'Tiêu đề',
    'schedule.leave.titlePlaceholder': 'VD: Nghỉ hè, Nghỉ nửa ngày chiều',
    'schedule.leave.date': 'Ngày',
    'schedule.leave.reason': 'Lý do chi tiết',
    'schedule.leave.reasonPlaceholder': 'Vui lòng nhập lý do chi tiết (Tùy chọn)',
    'schedule.leave.submit': 'Yêu cầu phê duyệt',

    // Header & Sidebar
    dashboard: 'Bảng điều khiển',
    projectBoard: 'Bảng dự án tổng hợp',
    projectIntake: 'Quản lý Đặt hàng/Phát triển',
    approvals: 'Lịch sử Phê duyệt',
    conflicts: 'Quản lý Xung đột Lịch',
    schedules: 'Lịch trình tổng hợp',
    notifications: 'Trung tâm Thông báo',
    settings: 'Cài đặt Vận hành',
    myTasks: 'Công việc của tôi',
    evaluation: 'Đánh giá Hiệu suất',

    // Board Columns
    preWork: 'Chưa bắt đầu',
    inProgress: 'Đang thực hiện',
    completed: 'Hoàn thành',
    revision: 'Chỉnh sửa',

    // Board Tabs
    devTeamWork: 'Công việc đội Phát triển',
    externalProject: 'Dự án Đặt hàng ngoài',

    // Board Time Badges
    goal: 'Mục tiêu',
    delivery: 'Giao hàng',
    overdue: '🚨 Quá hạn {label}',
    dueIn: 'Trước {time}',
    unset: 'Chưa đặt',

    // Intake
    newProjectReg: 'Đăng ký dự án mới',
    orderProjectManagement: 'Quản lý Dự án Đặt hàng',
    devTaskListManagement: 'Quản lý Danh sách Công việc Phát triển',

    // Settings
    translationSettings: 'Cài đặt Dịch thuật',
    workspaceSettings: 'Cài đặt Môi trường Vận hành',
    personnelManagement: 'Quản lý Nhân sự',
    bulkEdit: 'Đóng hàng loạt (Danger)',
    dataQuality: 'Kiểm tra Chất lượng Dữ liệu',
    importPreview: 'Nhập (JSON)',
    permissions: 'Cài đặt Chính sách Quyền',

    // Translation UI Warnings
    apiWarning: 'Lưu ý: Nội dung công việc nhạy cảm có thể được gửi đến máy chủ API miễn phí bên ngoài. Khuyên dùng máy chủ nội bộ khi vận hành chính thức.',
    fallbackManual: 'Vượt quá hạn mức dịch thuật miễn phí / Cần dịch thủ công',

    // Modal Tabs
    overview: 'Tổng quan',

    // P4-A Added Keys
    'header.role.superAdmin': 'Quản trị viên cấp cao',
    'header.role.systemAdmin': 'Quản trị hệ thống',
    'header.role.deptManager': 'Trưởng phòng',
    'header.role.pm': 'Quản lý dự án',
    'header.role.worker': 'Nhân viên',
    'header.dept.hq': 'Trụ sở chính',
    'header.dept.none': 'Không có trực thuộc',
    'header.loginRequired': 'Cần đăng nhập',
    'header.mode.real': 'Chế độ sử dụng thực tế',
    'header.mode.validation': 'Kiểm chứng vận hành',
    'header.data.prefix': 'Dữ liệu: ',
    'header.data.json': 'Vận hành JSON',
    'header.data.demo': 'Demo Seed',
    'header.data.excel': 'Nhập Excel',
    'header.data.empty': 'Trống',
    'header.nav.approvals': 'Hộp phê duyệt',
    'header.nav.evaluation': 'Đánh giá hiệu suất',

    'notification.title': 'Thông báo',
    'notification.readAll': 'Đánh dấu đã đọc tất cả',
    'notification.empty': 'Không có thông báo mới.',
    'notification.viewAll': 'Xem tất cả trung tâm thông báo',

    'settings.title': 'Cài đặt và Thông tin của tôi',
    'settings.loginRequired': 'Cần đăng nhập.',
    'settings.section.basicInfo': 'Thông tin cơ bản',
    'settings.field.name': 'Tên',
    'settings.field.role': 'Quyền (Role)',
    'settings.field.department': 'Phòng ban',
    'settings.field.emailMock': 'Email (Mock)',
    'settings.section.appSettings': 'Cài đặt ứng dụng',
    'settings.theme.dark': 'Chế độ tối',
    'settings.emailAlerts': 'Nhận email thông báo',
    'settings.note.backend': '* Cài đặt môi trường thực tế sẽ được áp dụng sau khi liên kết backend.',

    'common.progress': 'Tiến độ',

    // P4-B Added Keys
    'dashboard.loading': 'Đang tải...',
    'dashboard.title': 'Bảng điều khiển tổng hợp',
    'dashboard.subtitle': 'Tình trạng công việc chung',
    'dashboard.filter.allMonths': 'Xem tất cả các tháng',
    'common.yearMonth': 'Tháng {month} năm {year}',
    'dashboard.actions.importJson': 'Nhập JSON',
    'dashboard.actions.exportJson': 'Xuất JSON',

    'dashboard.metric.inProgressProject': 'Dự án đang thực hiện',
    'dashboard.metric.inProgressDesc': 'Tổng số dự án tháng này',
    'dashboard.metric.overdueProject': 'Dự án quá hạn giao hàng',
    'dashboard.metric.overdueDesc': 'Trong vòng 1 tuần hoặc đã quá hạn',
    'dashboard.metric.myTasks': 'Công việc của tôi',
    'dashboard.metric.myTasksDesc': 'Tổng công việc được giao',
    'dashboard.metric.completedTasks': 'Công việc đã hoàn thành',
    'dashboard.metric.completedTasksDesc': 'Công việc đã phê duyệt',
    'dashboard.metric.pending': 'Chờ phê duyệt',
    'dashboard.metric.pendingDesc': 'Chờ PM xem xét',
    'dashboard.metric.revision': 'Yêu cầu chỉnh sửa',
    'dashboard.metric.revisionDesc': 'Cần làm lại',

    'dashboard.sa.pendingApproval': 'Chờ kết toán/phê duyệt',
    'dashboard.sa.pendingApprovalDesc': 'Tài liệu đang chờ phê duyệt',
    'dashboard.sa.delayedTask': 'Công việc chậm trễ/xung đột',
    'dashboard.sa.delayedTaskDesc': 'Công việc quá hạn hoặc chưa xử lý',
    'dashboard.sa.projectSummary': 'Tóm tắt dự án hàng tháng',
    'dashboard.sa.emptyProject': 'Chưa có dự án nào để hiển thị.',
    'dashboard.sa.emptyProjectDesc': 'Vui lòng tải dữ liệu JSON hoặc đăng ký dự án mới.',

    'dashboard.dm.deptProject': 'Toàn bộ dự án của phòng ban',
    'dashboard.dm.deptProjectDesc': 'Các dự án đang tiến hành trong phòng',
    'dashboard.dm.pendingApproval': 'Chờ phê duyệt của nhân viên',
    'dashboard.dm.pendingApprovalDesc': 'Tài liệu cần trưởng phòng phê duyệt',
    'dashboard.dm.emptyProject': 'Không có dự án nào đang tiến hành trong phòng.',
    'dashboard.dm.emptyProjectDesc': 'Vui lòng nhận phân công mới hoặc tạo công việc từ bảng dự án.',

    'dashboard.pm.myProject': 'Dự án phụ trách',
    'dashboard.pm.myProjectDesc': 'Dự án được phân công làm PM',
    'dashboard.pm.pendingReview': 'Công việc chờ xem xét',
    'dashboard.pm.pendingReviewDesc': 'Tài liệu chờ xem xét kết quả công việc của nhóm',
    'dashboard.pm.emptyProject': 'Không có dự án nào đang phụ trách.',
    'dashboard.pm.emptyProjectDesc': 'Lịch sử dự án được phân công làm PM sẽ được hiển thị ở đây.',

    'dashboard.table.deliveryExpected': 'Ngày giao hàng dự kiến',
    'dashboard.table.targetExpected': 'Ngày mục tiêu dự kiến',

    'dashboard.section.recentTasks': 'Công việc được giao gần đây',
    'dashboard.empty.noTasks': 'Không có công việc được giao.',
    'dashboard.empty.noTasksDesc': 'Sẽ hiển thị ở đây khi PM giao việc.',
    'dashboard.table.taskName': 'Tên công việc',
    'dashboard.table.project': 'Dự án',
    'dashboard.table.projectName': 'Tên dự án',
    'dashboard.table.category': 'Loại',
    'dashboard.table.progress': 'Tiến độ',
    'dashboard.table.status': 'Trạng thái',
    'dashboard.table.dueDate': 'Ngày đến hạn',

    'dashboard.projectType.order': 'Đặt hàng',
    'dashboard.projectType.internal': 'Phát triển nội bộ',
    'common.unset': 'Chưa đặt',
    'dashboard.status.pending': 'Chờ phê duyệt',
    'dashboard.status.rejected': 'Bị từ chối',

    'dashboard.widget.workManagement': 'Quản lý công việc',
    'dashboard.work.inProgress': 'Đang thực hiện',
    'dashboard.work.qcPending': 'Chờ QC',
    'dashboard.work.upcomingDelivery': 'Sắp giao hàng',
    'dashboard.work.empty': 'Không có dự án tương ứng.',
    'dashboard.work.deptPm': 'Phòng ban/PM',
    'dashboard.work.targetDate': 'Ngày dự kiến hoàn thành',
    'dashboard.work.deliveryDate': 'Ngày giao hàng',
    'dashboard.work.progress': 'Tiến độ',
    'dashboard.work.deferredNote': '* Các chức năng gốc chi tiết chưa được triển khai (Deferred).',

    'dashboard.widget.managementSupport': 'Hỗ trợ quản lý',
    'dashboard.support.tabs.notice': 'Thông báo',
    'dashboard.support.tabs.hr': 'Tổ chức/Nhân sự',
    'dashboard.support.tabs.form': 'Biểu mẫu',
    'dashboard.support.noNotice': 'Không có thông báo nào được đăng ký.',
    'dashboard.support.important': 'Đọc bắt buộc',
    'dashboard.support.hrSummary': 'Tóm tắt thay đổi nhân sự (Tháng này)',
    'dashboard.support.newHires': 'Nhân viên mới',
    'dashboard.support.resigned': 'Nghỉ việc',
    'dashboard.support.deptStatus': 'Hiện trạng nhân sự theo phòng ban',
    'dashboard.support.noDeptData': 'Không có dữ liệu nhân sự phòng ban.',
    'dashboard.support.form.vacation': 'Mẫu đơn xin nghỉ phép',
    'dashboard.support.form.overtime': 'Mẫu đơn xin làm thêm',
    'dashboard.support.download': 'Tải xuống',
    'dashboard.support.peopleUnit': 'người',
  }
};

export const useTranslation = (lang: WorkspaceLanguage) => {
  return (key: keyof typeof UI_MESSAGES['ko'], params?: Record<string, string>) => {
    let str = UI_MESSAGES[lang]?.[key] || UI_MESSAGES['ko'][key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, v);
      });
    }
    return str;
  };
};

export const getUserDisplayName = (user: { name?: string; displayName?: string; role?: string; departmentName?: string; isKorean?: boolean } | null | undefined) => {
  if (!user) return 'Unknown';
  return user.displayName || user.name || 'Unknown';
};
